name: verify-pr-label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    if: github.event.pull_request.state == "open"
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "Pending Merge, Editorial"
